Ruby group capstone - Catalog of my things
AlselwiAisha/Ruby-Group-Capstone-Project pull request #51
Opened 2023-11-22 13:13 UTC by egichuhis

Hello, please review this PR. 

We are a team of 3 and we divided the particular tasks as follows: 

Team member #1: @egichuhis 
- book and label classes and methods
- add tables for book and label classes to schema

Team member #2: @HenaryKhuraijam 
- music_album and genre classes and methods
- add tables for music_album and genre classes to schema

Team member #3: @AlselwiAisha 
- game and author classes and methods
- add tables for game and author classes to schema

Write unit tests for respective class methods

Required Functionality Implemented:

1. List all books
2. List all music albums
3. List all movies
4. List of games
5. List all genres (e.g 'Comedy', 'Thriller')
6. List all labels (e.g. 'Gift', 'New')
7. List all authors (e.g. 'Stephen King')
8. List all sources (e.g. 'From a friend', 'Online shop')
9. Add a book
10. Add a music album
11. Add a movie
12. Add a game

- All data should be preserved by saving collections in .json files.
- Present the user with a list of options to perform.
- Let users choose an option.
- If needed, ask for parameters for the option.
- Have a way to quit the app.

2023-11-22 21:22 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @egichuhis @AlselwiAisha @HenaryKhuraijam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Unit tests are running without errors :+1: 
- PR is professional :+1: 


## Required Changes ♻️

- [ ] **Video presentation:** As mentioned in the [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md), we are supposed to present the features of this project in 5 minutes. All team members should appears in the video making the topic and the purpose of the project clear with a highlighted interesting piece of codes.

_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-22 21:22 UTC, FrederickMih commented on README.md
> +Feel free to check the [issues page](https://github.com/egichuhis/Ruby-Group-Capstone-Project/issues).
- [x] Hi team, let's kindly make sure this link is working as expected to facilitate someone to easily open an issue. I got a 404 error page when click on this link.

2023-11-22 21:22 UTC, FrederickMih commented on README.md
> +If you like this project please give it a star on [GitHub](https://github.com/egichuhis/Ruby-Group-Capstone-Project).
- [x] As stated above, all links to the project should be working in order to render the readme file professional.

2023-11-22 21:22 UTC, FrederickMih commented on lib/game.rb
> +class Game
- [x] Let kindly make sure  parent-child relationships is set up correctly as requested in the requirements. Based on the requirements, a Game should equally be an Item :+1:

2023-11-22 21:22 UTC, FrederickMih commented on lib/item.rb
> +  attr_accessor :id, :publish_date, :archived, :genre, :source, :author, :label
- [ ] I think genre, author and, label shouldn't be modify in this class. Again, id should always be read only.

2023-11-22 21:22 UTC, FrederickMih commented on lib/item.rb
> +class Item
- [ ] Let's kindly considered completely setting up associations between Item, Genre, Author and Label. Item class has one Genre, Author, and Label.

2023-11-22 21:22 UTC, FrederickMih commented on lib/game.rb
> +  end
- [ ] As requested in the requirements, let's kindly make sure this method override the method from the parent class(Item). The should return true if parent's method returns true **AND** if last_played_at is older than 2 years. Otherwise, it should return false.
- I think we can simply work with years to simplify this as you did in the Item class. Let's me know your thoughts about my reasoning :+1: 
 

```.ruby
  def can_be_archived?
     two_years_ago = Time.now.year - 2   # 2023 - 2 = 2021.
     super && @last_played < two_years_ago #  If game was last played at 2020 and can_be_archived? is true then this method should return true 
  end
```

2023-11-22 21:22 UTC, FrederickMih commented on app.rb
> +end
- [Optional] To minimized the length of this file size, we should have added these methods in the main.rb file.

2023-11-22 21:22 UTC, FrederickMih commented on app.rb
> +    print 'Enter cover state: '
- [Optional] Let's kindly display informative messages to our users who doesn't understand how the console app works. What should we expect from our user's to enter?. Let's make them understand what they are expected to enter: either good or bad :+1:

2023-11-22 21:22 UTC, FrederickMih commented on lib/book.rb
> +  end
![Screenshot from 2023-11-22 22-07-19](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/assets/63087491/f9a14545-14bd-4454-83b5-0fbba2f7a757)

2023-11-22 21:22 UTC, FrederickMih commented on data/books.json
> +[{"id":551,"publish_date":"2019-11-11","archived":false,"label":[],"publisher":"Reily Printers","cover_state":"New"},{"id":835,"publish_date":"2020-12-12","archived":false,"label":[],"publisher":"Hig
- [x] label was not correctly save in the json file as seen below. And above all the values are empty arrays. Let's fix it. In my case an object was save.
![Screenshot from 2023-11-22 22-15-46](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/assets/63087491/cab3bb32-6854-4cbb-b521-adf23c785b4c)

2023-11-24 10:05 UTC, V-Blaze requested changes
## Hi @egichuhis, @AlselwiAisha, @HenaryKhuraijam 

# Almost there 🟡 

![1094a3e620ebea4cd6cf2d0aceaa8f52](https://user-images.githubusercontent.com/107632780/229645999-eb4dcb1d-5a0c-4bdd-a150-2ab5cee3f40d.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
-  App runs as expected✔
- Meaningful commit mesages💯 🥇 ✔
- Correct git flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 10:05 UTC, V-Blaze commented on README.md
> +
- You have done great so far :+1: But there are a few requirements you still need to meet before moving to the next milestone. :+1: :100: 

- [ ] You did great adding the video presentation as the previous reviewer pointed out, but as stated in the project requirement, the video is meant to have a **Maximum** length of `5 mins`. Your current video has a length of about `11 mins` and that's against the requirement, I'll suggest you compress the video to meet the requirement or re-record the video. :small_airplane: :smile: 

- - Requirement:
 
![Screenshot from 2023-11-24 10-56-13](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/assets/107632780/2c7b640f-dc10-4419-b44d-47e0e90415a7)

2023-11-24 10:05 UTC, V-Blaze commented on lib/item.rb
> +    @label = nil
- [ ] As the previous reviewer suggested, you need to set up the association between the `Item` class and `Genre, Author and Label.`. currently, this has not been fully implemented correctly, I suggest you do so. :+1: :100: 

Here's a snippet of what it could look like:
```ruby
def add_genre(genre)
    @genre = genre
    genre.items.push(self) unless genre.items.include?(self)
  end

  def add_label(label)
    @label = label.title
    label.items << to_json unless label.items.include?(to_json)
  end

  # Adds the relation between Item and Author classes so that we can pass author as an object inside item
  def add_author(author)
    @author = author
    author.items << self
  end
```

2023-11-24 13:03 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi team, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the requested changes. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 13:04 UTC, merged